{"version":1,"defects":{"Tests\\Unit\\RouterTest::it_registers_a_route":4,"Tests\\Unit\\RouterTest::it_registers_a_get_route":4,"Tests\\Unit\\RouterTest::it_registers_a_post_route":4,"Tests\\Unit\\RouterTest::there_are_no_routes_when_router_is_created":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":4,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":4,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":4,"Tests\\Unit\\RouterTest::it_resolves_route":4},"times":{"Tests\\Unit\\RouterTest::it_registers_a_route":0.117,"Tests\\Unit\\RouterTest::it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::there_are_no_routes_when_router_is_created":0.008,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #0":0.031,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::it_processes_invoice":0.353,"Tests\\Unit\\Services\\InvoiceServiceTest::it_sends_receipt_email_when_invoice_is_processed":0.025}}